version: '2'
services:
  db:
    image: postgres:9.4
    volumes:
      - postgresql:/var/lib/postgresql/data
  redis:
    image: redis:3.2
  app: &rails_base
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - bundle:/usr/local/bundle
      - .:/usr/local/myapp:cached
    ports:
      - "3000:3000"
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: db
    depends_on:
      - db
      - redis
volumes:
  bundle:
  postgresql:
